//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wallmart.Database.Scripts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class City {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal City() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wallmart.Database.Scripts.City", typeof(City).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* Add */
        ///
        ///--declare @name as varchar(50); set @name = &apos;Osasco&apos;
        ///--declare @stateId as int;set @stateId = 4
        ///--declare @isCapital as bit;set @isCapital = 0
        ///
        ///insert into Cities 
        ///	(cit_name,
        ///	cit_stateId,
        ///	cit_isCapital)
        ///values
        ///	(@name,
        ///	@stateId,
        ///	@isCapital)
        ///
        ///
        ///select SCOPE_IDENTITY().
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* ListAll */
        ///
        ///select 
        ///	cit_cityId [cityId],
        ///	cit_name [name],
        ///	cit_stateId [stateId],
        ///	cit_isCapital [isCapital]
        ///from Cities.
        /// </summary>
        internal static string ListAll {
            get {
                return ResourceManager.GetString("ListAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* ListByName */
        ///
        ///--declare @name varchar(50);
        ///--set @name = &apos;osa&apos;;
        ///
        ///select 
        ///	cit_cityId [cityId],
        ///	cit_name [name],
        ///	cit_stateId [stateId],
        ///	cit_isCapital [isCapital]
        ///from Cities 
        ///where 
        ///	cit_name like &apos;%&apos; + @name + &apos;%&apos;.
        /// </summary>
        internal static string ListByName {
            get {
                return ResourceManager.GetString("ListByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* Remove */
        ///
        ///--declare @cityId int;
        ///--set @cityId  = 15;
        ///
        ///delete Cities 
        ///where cit_cityId = @cityId.
        /// </summary>
        internal static string RemoveById {
            get {
                return ResourceManager.GetString("RemoveById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* UpdateById */
        ///
        ///--declare @name as varchar(50); set @name = &apos;Osasco&apos;
        ///--declare @stateId as int;set @stateId = 4
        ///--declare @isCapital as bit;set @isCapital = 0
        ///
        ///update Cities set cit_name = @name,
        ///	cit_stateId = @stateId,
        ///	cit_isCapital = @isCapital
        ///where cit_cityId = @cityId.
        /// </summary>
        internal static string UpdateById {
            get {
                return ResourceManager.GetString("UpdateById", resourceCulture);
            }
        }
    }
}
