//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wallmart.Database.Scripts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class State {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal State() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wallmart.Database.Scripts.State", typeof(State).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* Add */
        ///
        ///--declare @name as varchar(50); set @name = &apos;goias&apos;
        ///--declare @abbreviation as varchar(2);set @abbreviation = &apos;GO&apos;
        ///--declare @regionId as int;set @regionId = 1
        ///--declare @country as varchar(50);set @country = &apos;Brasil&apos;
        ///
        ///
        ///insert into States
        ///	(sta_name,
        ///	sta_abbreviation,
        ///	sta_regionId,
        ///	sta_country)
        ///values
        ///	(@name, 
        ///	@abbreviation,
        ///	@regionId,
        ///	@country)
        ///
        ///select SCOPE_IDENTITY().
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* ListAll */
        ///
        ///select 
        ///	sta_stateId [stateId],
        ///	sta_name [name],
        ///	sta_abbreviation [abbreviation],
        ///	sta_regionId [regionId],
        ///	sta_country [country]
        ///from States.
        /// </summary>
        internal static string ListAll {
            get {
                return ResourceManager.GetString("ListAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* ListByName */
        ///
        ///--declare @name varchar(50);
        ///--set @name = &apos;sao&apos;;
        ///
        ///select 
        ///	sta_stateId [stateId],
        ///	sta_name [name],
        ///	sta_abbreviation [abbreviation],
        ///	sta_regionId [regionId],
        ///	sta_country [country]
        ///from States
        ///	where sta_name like &apos;%&apos; + @name + &apos;%&apos;.
        /// </summary>
        internal static string ListByName {
            get {
                return ResourceManager.GetString("ListByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* Remove */
        ///
        ///--declare @stateId int;
        ///--set @stateId  = 1;
        ///
        ///delete States
        ///where sta_stateId = @stateId.
        /// </summary>
        internal static string RemoveById {
            get {
                return ResourceManager.GetString("RemoveById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* UpdateById */
        ///
        ///--declare @name as varchar(50); set @name = &apos;goias&apos;
        ///--declare @abbreviation as varchar(2);set @abbreviation = &apos;GO&apos;
        ///--declare @regionId as int;set @regionId = 1
        ///--declare @country as varchar(50);set @country = &apos;Brasil&apos;
        ///
        ///update States set
        ///	sta_name = @name,
        ///	sta_abbreviation = @abbreviation,
        ///	sta_regionId = @regionId,
        ///	sta_country = @country
        ///where 
        ///	sta_stateId = @stateId.
        /// </summary>
        internal static string UpdateById {
            get {
                return ResourceManager.GetString("UpdateById", resourceCulture);
            }
        }
    }
}
